# Generated by Django 4.2.30 on 2026-09-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_tecnologia_remove_proyecto_tecnologia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiquetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='website.tecnologia'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='website.etiquetas'),
        ),
    ]
